routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/single/{slug}', 'HomeController@single')->name('product.single');

Route::get('/category/{slug}','ViewProductCategoryController@index')->name('category.single');
Route::get('/store/{slug}','ViewProductStoreController@index')->name('store.single');

Route::prefix('cart')->name('cart.')->group(function(){

    Route::get('/', 'CartController@index')->name('index');
    Route::post('add', 'CartController@add')->name('add');
    Route::get('remove/{slug}', 'CartController@remove')->name('remove');
    Route::get('cancel', 'CartController@cancel')->name('cancel');

});

Route::prefix('checkout')->name('checkout.')->group(function(){
    Route::get('/','CheckoutController@index')->name('index');
    Route::post('/processCheckout', 'CheckoutController@processCheckout')->name('processCheckout');
    Route::get('/thanks', 'CheckoutController@thanks')->name('thanks');
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('my-orders', 'UserOrderController@index')->name('user.orders');

    Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {

      Route::get('notifications', 'NotificationController@notifications')->name('notifications.index');
      Route::get('notifications/read-all', 'NotificationController@readAll')->name('notifications.read.all');  
      Route::get('notifications/read/{id}', 'NotificationController@read')->name('notifications.read');  
  

//    Route::prefix('stores')->name('stores.')->group(function(){
//
//        Route::get('/', 'StoreController@index')->name('index');
//
//        Route::get('/create', 'StoreController@create')->name('create');
//
//        Route::post('/store', 'StoreController@store')->name('store');
//
//        Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
//
//        Route::post('/update/{store}', 'StoreController@update')->name('update');
//
//        Route::get('/destroy/{store}', 'StoreController@destroy')->name('destroy');
//
//    });


        Route::resource('categories', 'CategoryController');

        Route::resource('stores', 'StoreController');

        Route::resource('products', 'ProductController');

        Route::post('photos/remove', 'ProductPhotoController@removePhoto')->name('photo.remove');

        Route::get('orders/my', 'OrdersController@index')->name('orders.my');

    });

});

Auth::routes();

resources/views/cart.blade.php
@extends('layouts.front')

@section('content')

    <div class="row">
        <div class="col-12">
            <h2>Carrinho de Compra</h2>
            <hr>
        </div>
        <div class="col-12">
            @if ($cart)
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Produto</th>
                        <th>Preço</th>
                        <th>Qantidade</th>
                        <th>Subtotal</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php $total = 0; @endphp
                    @foreach($cart as $product)
                        <tr>
                            <td>{{$product['name']}}</td>
                            <td>R$ {{number_format($product['price'] , 2, ',', '.' )}}</td>
                            <td>{{$product['amount']}}</td>
                            <td>R$ {{number_format($product['price'] * $product['amount'], 2, ',', '.')}}</td>
                            @php
                                $subtotal = $product['price'] * $product['amount'];
                                $total += $subtotal;
                            @endphp
                            <td>
                                <a href="{{route('cart.remove', ['slug' => $product['slug']])}}" class="btn btn-sm btn-danger">Remover</a>
                            </td>
                        </tr>
                    @endforeach
                    <tr>
                        <td colspan="3">Total</td>
                        <td colspan="2">{{number_format($total, 2, ',', '.')}}</td>
                    </tr>
                    </tbody>
                </table>
                <hr>
                <div class="col-md-12">
                    <a href="{{route('checkout.index')}}" class="btn btn-lg btn-success pull-right">Concluir Compra</a>
                    <a href="{{route('cart.cancel')}}" class="btn btn-lg btn-danger pull-left">Cancelar Compra</a>
                </div>
            @else
                <div class="alert alert-warning">Carrinho vazio!</div>
            @endif
        </div>
    </div>
@endsection

resources/views/category.blade.php
@extends('layouts.front')

@section('content')

    <div class="row front">
        <div class="col-12">
        <h2>{{$category->name}}</h2>
        <hr>
        </div>
        @forelse($category->products as $key => $product)
                <div class="col-md-4">
                    <div class="card">
                        @if ($product->photos->count())
                            <img style="width: 98%" src="{{asset('storage/'.$product->photos->first()->image)}}"
                                class="img-fluid" alt="">
                        @else
                            <img style="width: 98%" src="{{asset('assets/img/no-photo.jpg')}}"
                                class="img-fluid" alt="">
                        @endif
                        <div class="card-body">
                            <h2 class="card-title">{{$product->name}}</h2>
                            <p class="card-text">{{$product->description}}</p>
                            <h3>R$ {{number_format($product->price, '2', ',', '.')}}</h3>
                            <a href="{{route('product.single', ['slug' =>$product->slug])}}" class="btn btn-success">Ver Produto</a>

                        </div>
                    </div>
                </div>
                @if (($key + 1) % 3 == 0)
                    </div><div class="row front">
                @endif
        @empty
            <h3 class="alert alert-warning">
                Nenhum produto encontrado com essa categoria.
            </h3>
        @endforelse  
    </div>
@endsection

resources/views/checkout.blade.php
@extends('layouts.front')

@section('stylesheets')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
@endsection

@section('content')

    <div class="container">
        <div class="col-md-6">

            <div class="row">
                <div class="col-md-12">
                    <h2>Dados para Pagamento </h2>
                </div>
            </div>

            <hr>
            <form action="" method="post">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label>Número do Cartão <span class="brand"></span></label>
                        <input type="text" class="form-control" name="card_number">
                        <input type="hidden" class="form-control" name="card_brand">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label>Nome no cartão <span class="brand"></span></label>
                        <input type="text" style="text-transform: uppercase" class="form-control" name="card_name">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 form-group">
                        <label>Mês de expiração</label>
                        <input type="text" class="form-control" name="card_month">
                    </div>

                    <div class="col-md-4 form-group">
                        <label>Ano de expiração</label>
                        <input type="text" class="form-control" name="card_year">
                    </div>
                </div>


                <div class="row">
                    <div class="col-md-5 form-group">
                        <label>Código de segurança</label>
                        <input type="text" class="form-control" name="card_cvv">
                    </div>

                    <div class="col-md-12 installments form-group"></div>
                </div>

                <button class="btn btn-success btn-lg processCheckout">Efetuar pagamento</button>
            </form>
        </div>
    </div>

    <div></div>
@endsection
@section('scripts')
    <script src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="{{ asset('assets/js/jquery.ajax.js') }}"></script>
   


    <script>
        //session code que vem do back
        const sessionId = '{{ session()->get('pagseguro_session_code') }}'
        //passando para a lib js do proprio pagseguro
        PagSeguroDirectPayment.setSessionId(sessionId)

    </script>
    <script>
        let amountTransaction = '{{ $cartItems }}'

        let cardNumber = document.querySelector('input[name=card_number]')

        let spanBrand = document.querySelector('span.brand')

        cardNumber.addEventListener('keyup', function() {

            if (cardNumber.value.length >= 6) {
                //metodo que traz info do cartao
                PagSeguroDirectPayment.getBrand({
                    //a partir da casa zero vai pegar 6 digitos
                    cardBin: cardNumber.value.substr(0, 6),
                    success: function(res) {
                        let imgFlag =`<img src="https://stc.pagseguro.uol.com.br/public/img/payment-methods-flags/68x30/${res.brand.name}.png">`
                        spanBrand.innerHTML = imgFlag
                        document.querySelector('input[name=card_brand]').value = res.brand.name
                        getInstallments(amountTransaction, res.brand.name)
                    },
                    error: function(err) {
                        console.log(err)
                    }
                })
            }
        })

        //gerar token do cartao
        let submitButton = document.querySelector('button.processCheckout')

        submitButton.addEventListener('click', function(event) {
            //para nao executar o evento padrao de submit
            event.preventDefault()

            PagSeguroDirectPayment.createCardToken({
                cardNumber: document.querySelector('input[name=card_number]').value,
                brand: document.querySelector('input[name=card_brand]').value,
                cvv: document.querySelector('input[name=card_cvv]').value,
                expirationMonth: document.querySelector('input[name=card_month]').value,
                expirationYear: document.querySelector('input[name=card_year]').value,
                success: function(res) {
                    processPayment(res.card.token)
                },
                error: function(err) {
                    console.log(err)
                }
            })
        })



        function processPayment(token) {
            let data = {
                card_token: token,
                //retorna hash que identifica esse usuário para a requisição do pagamento
                hash: PagSeguroDirectPayment.getSenderHash(),
                installment: document.querySelector('.select_installments').value,
                _token: '{{ csrf_token() }}',
                card_name: document.querySelector('input[name=card_name]').value,
            }

            $.ajax({
                type: 'POST',
                url: '{{ route('checkout.processCheckout') }}',
                data: data,
                dataType: 'json',
                success: function(res) {
                    toastr.success(res.data.message, 'Sucesso')
                    window.location.href = ('{{ route('checkout.thanks') }}?order=' + res.data.order)
                }
            })
        }


        //recebe total da compra e nome da bandeira
        function getInstallments(amount, brand) {
            PagSeguroDirectPayment.getInstallments({
                amount: amount,
                brand: brand,
                //quantidade de parcelas em que não há juros
                maxInstallmentNoInterest: 0,
                success: function(res) {

                    let selectInstallments = drawSelectInstallments(res.installments[brand])
                    document.querySelector('div.installments').innerHTML = selectInstallments
                },
                error: function(err) {
                    console.log(err)
                }
            })

        }

        //mostrar select de parcelas
        function drawSelectInstallments(installments) {
            let select = '<label>Opções de Parcelamento:</label>';

            select += '<select class="form-control select_installments">';

            for (let l of installments) {
                select +=
                    `<option value="${l.quantity}|${l.installmentAmount}">${l.quantity}x de ${l.installmentAmount} - Total fica ${l.totalAmount}</option>`;
            }

            select += '</select>';

            return select;
        }

    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/single.blade.php
@extends('layouts.front')

@section('content')

    <div class="row">
        <div class="col-4">
            @if ($product->photos->count())
                <img style="width: 98%" src="{{asset('storage/'.$product->photos->first()->image)}}"
                     class="img-fluid" alt="">
                <div class="row mt-3">
                    @foreach($product->photos as $photo)
                        <div class="col-4">
                            <img style="width: 98%" src="{{asset('storage/'.$photo->image)}}"
                                 class="img-fluid" alt="">
                        </div>
                    @endforeach
                </div>
            @else
                <img style="width: 98%" src="{{asset('assets/img/no-photo.jpg')}}"
                     class="img-fluid" alt="">
            @endif
        </div>
        <div class="col-6">
            <div class="col-md-12">
                <h2>{{$product->name}}</h2>
                <p>{{$product->description}}</p>
                <h3>R$ {{number_format($product->price, '2', ',', '.')}}</h3>

                <span>
                    Loja: {{$product->store->name}}
            </span>
            </div>
            <div class="product-add col-md-12">
                <hr>
                <form action="{{route('cart.add')}}" method="POST">
                    @csrf
                    <input type="hidden" name="product[name]" value="{{$product->name}}">
                    <input type="hidden" name="product[price]" value="{{$product->price}}">
                    <input type="hidden" name="product[slug]" value="{{$product->slug}}">
                    <div class="form-group">
                        <label for="">Quantidade</label>
                        <input type="number" name="product[amount]" class="fomr-control col-md-2 mt-2" value="1">
                    </div>
                    <button type="submit" class="btn btn-lg btn-danger mt-2">Comprar</button>
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <hr>
            {{$product->body}}
        </div>
    </div>
@endsection

resources/views/store.blade.php
@extends('layouts.front')

@section('content')

    <div class="row front">
        <div class="col-12">
            <h2>{{$store->name}}</h2>
            <p>{{$store->description}}</p>
            <p>
                <strong>Contatos:</strong>
            <span>{{$store->phone}}</span> | <span>{{$store->mobile_phone}}</span>
            </p>
        </div>
        <div class="col-12">
            <h2>Produtos desta loja:</h2>
        </div>
        @forelse($store->products as $key => $product)
                <div class="col-md-4">
                    <div class="card">
                        @if ($product->photos->count())
                            <img style="width: 98%" src="{{asset('storage/'.$product->photos->first()->image)}}"
                                class="img-fluid" alt="">
                        @else
                            <img style="width: 98%" src="{{asset('assets/img/no-photo.jpg')}}"
                                class="img-fluid" alt="">
                        @endif
                        <div class="card-body">
                            <h2 class="card-title">{{$product->name}}</h2>
                            <p class="card-text">{{$product->description}}</p>
                            <h3>R$ {{number_format($product->price, '2', ',', '.')}}</h3>
                            <a href="{{route('product.single', ['slug' =>$product->slug])}}" class="btn btn-success">Ver Produto</a>

                        </div>
                    </div>
                </div>
                @if (($key + 1) % 3 == 0)
                    </div><div class="row front">
                @endif
        @empty
            <h3 class="alert alert-warning">
                Nenhum produto encontrado para essa loja.
            </h3>
        @endforelse  
    </div>
@endsection

resources/views/thanks.blade.php
@extends('layouts.front')

@section('content')

    <h1 class="alert success">
        Muito obrigado pela sua compra!
    </h1>
    <h2 class="alert success">
        Seu pedido foi processado, código do pedido: {{request()->get('order')}}
    </h2>

@endsection

resources/views/user-orders.blade.php
@extends('layouts.front')

@section('content')

<div class="row">
    <div class="col-12">
        <h2>Meus Pedidos</h2>
        <hr>
    </div>

    <div class="col-12">
        <div class="accordion" id="accordionExample"> 

          @forelse($userOrders as $key => $order)
            <div class="card">
              <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{$key}}" aria-expanded="true" aria-controls="collapseOne">
                    Pedido número: {{$order->reference}}
                  </button>
                </h2>
              </div>
          
            <div id="collapse{{$key}}" class="collapse @if($key == 0) show @endif" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                  <ul>

                    @php $items = unserialize($order->items); @endphp

                    @foreach ($items as $item)
                        <li>{{$item['name']}} | R$ {{number_format($item['price'], 2, ',','.')}}</li>
                        <li>Quantidade pedida: {{$item['amount']}}</li>
                    @endforeach

                  </ul>

                </div>
              </div>
            </div>
            @empty  
              <div class="alert alert-warning">Nenhum pedido recebido!</div>
            @endforelse
    </div>

    <div class="col-12">
      <hr>
      {{$userOrders->links()}}
    </div>

    
</div>

@endsection()