routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/single/{slug}', 'HomeController@single')->name('product.single');

Route::get('/category/{slug}','ViewProductCategoryController@index')->name('category.single');
Route::get('/store/{slug}','ViewProductStoreController@index')->name('store.single');

Route::prefix('cart')->name('cart.')->group(function(){

    Route::get('/', 'CartController@index')->name('index');
    Route::post('add', 'CartController@add')->name('add');
    Route::get('remove/{slug}', 'CartController@remove')->name('remove');
    Route::get('cancel', 'CartController@cancel')->name('cancel');

});

Route::prefix('checkout')->name('checkout.')->group(function(){
    Route::get('/','CheckoutController@index')->name('index');
    Route::post('/processCheckout', 'CheckoutController@processCheckout')->name('processCheckout');
    Route::get('/thanks', 'CheckoutController@thanks')->name('thanks');
});

Route::group(['middleware' => ['auth']], function () {

    Route::get('my-orders', 'UserOrderController@index')->name('user.orders');

    Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {

      Route::get('notifications', 'NotificationController@notifications')->name('notifications.index');
      Route::get('notifications/read-all', 'NotificationController@readAll')->name('notifications.read.all');  
      Route::get('notifications/read/{id}', 'NotificationController@read')->name('notifications.read');  
  

//    Route::prefix('stores')->name('stores.')->group(function(){
//
//        Route::get('/', 'StoreController@index')->name('index');
//
//        Route::get('/create', 'StoreController@create')->name('create');
//
//        Route::post('/store', 'StoreController@store')->name('store');
//
//        Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
//
//        Route::post('/update/{store}', 'StoreController@update')->name('update');
//
//        Route::get('/destroy/{store}', 'StoreController@destroy')->name('destroy');
//
//    });


        Route::resource('categories', 'CategoryController');

        Route::resource('stores', 'StoreController');

        Route::resource('products', 'ProductController');

        Route::post('photos/remove', 'ProductPhotoController@removePhoto')->name('photo.remove');

        Route::get('orders/my', 'OrdersController@index')->name('orders.my');

    });

});

Auth::routes();

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Product extends Model
{
    use HasSlug;

    protected $fillable = ['name', 'description', 'body', 'price', 'slug'];


    public function store()
    {
        return $this->belongsTo(Store::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function photos()
    {
        return $this->hasMany(ProductPhoto::class);
    }

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('slug')
            ;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Product;
use App\Store;
use App\Traits\UploadTrait;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    use UploadTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $store = auth()->user()->store;

        $products = Product::where('store_id', $store->id)->paginate(10);

        return view('admin.products.index', [
            'products' => $products,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all(['id', 'name']);
        return view('admin.products.create', [
            'categories' => $categories,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {

        $data = $request->all();

        $categories = $request->get('categories', null);

        $store = auth()->user()->store;
        $product = $store->products()->create($data);
        $product->categories()->sync($categories);

        if($request->hasFile('photos')){
            $images = $this->imageUpload($request->file('photos'), 'image');
            //inserir referencia na base
            $product->photos()->createMany($images);
        }

        flash('Produto criado com sucesso!')->success();
        return redirect()->route('admin.products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        $categories = Category::all(['id', 'name']);

        return view('admin.products.edit', [
            'product' => $product,
            'categories' => $categories,
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $data = $request->all();

        $categories = $request->get('categories', null);

        $product = Product::find($id);
        $product->update($data);
        
        if (!isset($data['categories'])) {
            $product->categories()->detach();
        } else {
            $product->categories()->sync($data['categories']);

        }

        if($request->hasFile('photos')){
            $images = $this->imageUpload($request->file('photos'), 'image');
            //inserir referencia na base
            $product->photos()->createMany($images);
        }

        $categories = Category::all(['id', 'name']);

        flash('Produto alterado com sucesso!')->success();
        return redirect()->route('admin.products.edit', [
            'product' => $product,
            'categories' => $categories,
        ]);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->categories()->detach($id);
        $product->delete();
        flash('Produto removido com sucesso!')->success();
        return redirect()->route('admin.products.index');

    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mt-2">Criar produto</h1>

    <form action="{{ route('admin.products.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label>Nome</label>
            <input class="form-control @error('name') is-invalid @enderror" type="text" name="name"
                   value="{{old('name')}}">
            @error('name')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input class="form-control @error('description') is-invalid @enderror" type="text" name="description"
                   value="{{old('description')}}">
            @error('description')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Conteúdo</label>
            <textarea name="body" id="" cols="30" rows="10"
                      class="form-control @error('body') is-invalid @enderror">{{old('body')}}</textarea>
            @error('body')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Preço</label>
            <input class="form-control @error('price') is-invalid @enderror" type="text" name="price"
                   value="{{old('price')}}">
            @error('price')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <label>Categorias</label>
            <select id="select-categories" name="categories[]" class="form-control" multiple>
                @foreach($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="">Fotos do produto</label>
            <input type="file" name="photos[]" class="form-control @error('photos') is-invalid @enderror" multiple="multiple">
            @error('photos')
                <div class="invalid-feedback">
                    {{$message}}
                </div>
            @enderror
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-lg btn-success">Criar Produto</button>
        </div>

    </form>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mt-2">Editar produto</h1>

    <form action="{{ route('admin.products.update', ['product' => $product->id]) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method("PUT")
        <input type="hidden" name="_method" value="PUT">
        <div class="form-group">
            <label>Nome</label>
            <input class="form-control" type="text" name="name" value="{{$product->name}}">
        </div>

        <div class="form-group">
            <label>Descrição</label>
            <input class="form-control" type="text" name="description" value="{{$product->description}}">
        </div>

        <div class="form-group">
            <label>Conteúdo</label>
            <textarea name="body" id="" cols="30" rows="10" class="form-control">{{$product->body}}</textarea>
        </div>

        <div class="form-group">
            <label>Preço</label>
            <input class="form-control" type="text" name="price" value="{{$product->price}}">
        </div>

        <div class="form-group">
            <label>Categorias</label>
            <select id="select-categories" name="categories[]" class="form-control" multiple>
                @foreach($categories as $category)
                    <option value="{{$category->id}}" @if($product->categories->contains($category)) selected @endif >{{$category->name}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="">Fotos do produto</label>
            <input type="file" name="photos[]" class="form-control @error('photos') is-invalid @enderror" multiple="multiple">
            @error('photos')
            <div class="invalid-feedback">
                {{$message}}
            </div>
            @enderror
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-lg btn-success">Atualizar Produto</button>
        </div>

    </form>

    <hr>

    <div class="row">
        @foreach($product->photos as $photo)
            <div class="col-4 text-center">
                <img src="{{ asset('storage/'.$photo->image)  }}" alt="" class="img-fluid">
                <form action="{{route('admin.photo.remove')}}" method="POST">
                @csrf
                <input type="hidden" name="photoName" value="{{$photo->image}}">
                <button type="submit" class="btn btn-lg btn-danger">X</button>
                </form>
            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
    <h1 class="mt-2">Lista de Produtos</h1>
    <a href="{{ route('admin.products.create')  }}" class="btn btn-sm btn-success mt-1 mb-1">Novo Produto</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Nome</th>
            <th>Preço</th>
            <th>Loja</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
            <tr>
                <td>{{ $product->id }}</td>
                <td>{{ $product->name }}</td>
                <td>R$ {{ number_format($product->price, 2, ',', '.') }}</td>
                <td>{{ $product->store->name }}</td>
                <td>
                    <div class="btn-group">
                        <a href="{{ route('admin.products.edit', ['product' =>$product->id])  }}" class="btn btn-sm btn-primary mr-2">EDITAR</a>
                        <form action="{{ route('admin.products.destroy', ['product' =>$product->id]) }}" method="post">
                            @csrf
                            @method("DELETE")
                            <button class="btn btn-sm btn-danger" type="submit">REMOVER</button>
                        </form>
                    </div>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {{$products->links()}}

@endsection